CREATE TABLE IF NOT EXISTS car (
                                        car_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        brand VARCHAR,
                                        model VARCHAR,
                                        category VARCHAR,
                                        state_number VARCHAR UNIQUE,
                                        type VARCHAR,
                                        year_of_release int,
                                        trailer boolean,
                                        CONSTRAINT pk_car PRIMARY KEY (car_id)
--                                         CONSTRAINT UQ_state_numder UNIQUE (state_number)
    );